### ISSUE TITLE
请问下 sh_op 是定义了什么

### ISSUE THREAD

**Issue by wojiushixiaobai** [zhangguanzhang/docker-compose-aarch64#1]
```yaml
- name: build docker-compose 
        id: build
        run: |
          bash  ${{ secrets.sh_op }} build.sh
```
我看到任务里有用到，但是没从 build.sh 里面看到引用的方法
